sudo: required
language: cpp

env:
  global:
    - OMP_NUM_THREADS=2
    - APPROXMVBB_CACHE_DIR="$HOME/ApproxMVBBCache"

cache:
  directories:
  - $APPROXMVBB_CACHE_DIR

matrix:
  include:
  - env: USE_GCC="YES" GCC_VERSION="5"
    os: linux
    dist: xenial
    addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

  - env: USE_GCC="YES" GCC_VERSION="6"
    os: linux
    dist: xenial
    addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

  - env: USE_CLANG="YES" CLANG_VERSION=""
    os: linux
    dist: xenial
    addons: &clang7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

  - env: USE_CLANG="YES" CLANG_VERSION=""
    os: linux
    dist: focal

  - env: USE_GCC="YES" GCC_VERSION=""
    os: linux
    dist: focal

  - env: APPLE_CLANG="YES" MANUAL_EIGEN="OFF"
    os: osx
    osx_image: xcode11.2
    compiler: clang

  - env: APPLE_CLANG="NO" MANUAL_EIGEN="OFF"
    os: osx
    osx_image: xcode11.2
    compiler: clang

# Install dependencies
install:
  - export ROOT_PATH=`pwd`/../;
  - export CHECKOUT_PATH=`pwd`;
  - export BRANCH_NAME=$TRAVIS_BRANCH

  - mkdir -p $APPROXMVBB_CACHE_DIR/{bin,include,lib,share}
  - export INSTALL_PREFIX="$APPROXMVBB_CACHE_DIR"
  - export PATH="$INSTALL_PREFIX/bin:/usr/local/bin:$PATH"
  - export CMAKE_PREFIX_PATH="$APPROXMVBB_CACHE_DIR;/usr/local"

  - chmod +x $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh
  - $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh

script:
  - chmod +x $CHECKOUT_PATH/travis/build.sh
  - $CHECKOUT_PATH/travis/build.sh

after_success:
  - cd $CHECKOUT_PATH
  - git reset --hard HEAD # Discard build artifacts
  - git clean -df # Discard build artifacts

notifications:
  email: false
